import './globals.css';
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';

import { cn } from '@/lib/utils';
import { AuthProvider } from '@/components/providers/AuthProvider';
import { ThemeProvider } from '@/components/providers/ThemeProvider';
import { ModalProvider } from '@/components/providers/ModalProvider';
import { WebSocketProvider } from '@/components/providers/SocketProvider';
import { QueryProvider } from '@/components/providers/QueryProvider';
import { ParticipantProvider } from '@/components/providers/ParticipantProvider';

const inter = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Team Chat Application',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className='h-full' suppressHydrationWarning>
      <body
        className={cn(
          inter.className,
          "bg-white dark:bg-[#313338] h-full"
        )}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='dark'
          enableSystem={false}
          storageKey='discord-theme'
        >
          <AuthProvider>
            <WebSocketProvider>
              <ParticipantProvider>
                <ModalProvider />
                <QueryProvider>
                  {children}
                </QueryProvider>
              </ParticipantProvider>
            </WebSocketProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
