import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { AuthProvider } from '@/components/providers/auth-provider';
import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/components/providers/theme-provider'

const inter = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Team Chat Application',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
      <html>
        <body className={cn(
          inter.className,
          "bg-white dark:bg-[#313338]"
        )}>
          <ThemeProvider
            attribute='class'
            defaultTheme='dark'
            enableSystem={false}
            storageKey='discord-theme'
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </AuthProvider>
  )
}
